# -*- coding: utf-8 -*-
"""UAS_KecerdasanBuatan.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pwiolQY4RzDmSLThmkce_Cy6DGU6mOpO
"""

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.naive_bayes import GaussianNB

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report

from google.colab import drive
drive.mount('/content/drive')

# GANTI PATH SESUAI FILE LO
df = pd.read_csv('/content/drive/MyDrive/KecerdasanBuatan_UAS/migraine.csv')
df.head()

# Tentukan target
TARGET = 'Type'

X = df.drop(columns=[TARGET])
y = df[TARGET]

X.shape, y.value_counts()

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
y_encoded = le.fit_transform(y)

# Lihat mapping kelas
label_mapping = dict(zip(le.classes_, le.transform(le.classes_)))
label_mapping

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y_encoded,
    test_size=0.2,
    random_state=42,
    stratify=y_encoded
)

X_train.shape, X_test.shape

from sklearn.naive_bayes import GaussianNB

model = GaussianNB()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report

print("Accuracy :", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred, average='weighted'))
print("Recall   :", recall_score(y_test, y_pred, average='weighted'))
print("F1-score :", f1_score(y_test, y_pred, average='weighted'))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

from sklearn.model_selection import StratifiedKFold, cross_val_score

cv = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)
scores = cross_val_score(model, X, y_encoded, cv=cv, scoring='accuracy')

scores.mean(), scores.std()